AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - com.sysco.lambdatest::com-sysco-lambdatest
Resources:
  LambdaTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.sysco.lambdatest.LambdaHandler::handleRequest
      Runtime: java8
      CodeUri: build/libs/java-springboot-lambda-test-1.0-SNAPSHOT-all.jar
      MemorySize: 1024
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        Greeting:
          Type: Api
          Properties:
            Path: /v1.0/greeting
            Method: any

        Hello:
          Type: Api
          Properties:
            Path: /v1.0/hello
            Method: any

Outputs:
  LambdaTestApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: LambdaTestApi
